[project]
name = "mcp-servers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "todd zhang", email = "toddzhang@pathintegral.xyz" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
mcp-servers = "mcp_servers:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.workspace]
members = ["servers/txyz-search", "servers/fetch"]